"""test_level15.py

Correctness of the blind-play scoring and the causal trading play.
Deterministic; standard library + pytest only.
"""

from __future__ import annotations

import math
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "level5"))

from blindplay import (roc_auc, brier, reliability, oos_event_forecast,  # noqa: E402
                       causal_dc_equity, buy_hold)


def test_roc_auc_perfect_and_random():
    # high scores on the positives -> AUC 1.0
    assert roc_auc([0.1, 0.2, 0.8, 0.9], [0, 0, 1, 1]) == 1.0
    # high scores on the negatives -> AUC 0.0
    assert roc_auc([0.1, 0.2, 0.8, 0.9], [1, 1, 0, 0]) == 0.0
    # all-equal scores -> 0.5 (no skill)
    assert abs(roc_auc([0.5, 0.5, 0.5, 0.5], [0, 1, 0, 1]) - 0.5) < 1e-9


def test_roc_auc_degenerate_labels():
    assert roc_auc([0.1, 0.9], [1, 1]) == 0.5
    assert roc_auc([0.1, 0.9], [0, 0]) == 0.5


def test_brier_bounds():
    assert brier([1.0, 0.0], [1, 0]) == 0.0
    assert brier([0.0, 1.0], [1, 0]) == 1.0


def test_reliability_bins_sum():
    scores = [0.05, 0.15, 0.95, 0.96]
    labels = [0, 0, 1, 1]
    rel = reliability(scores, labels, nbins=10)
    assert sum(r["n"] for r in rel) == len(scores)


def test_oos_forecast_shapes_and_labels():
    # events every 20 days; a forecast at t should sometimes see an event within horizon
    events = list(range(100, 2000, 20))
    scores, labels = oos_event_forecast(events, 2000, mu=0.01, alpha=0.2, beta=0.1,
                                        t_train=1000, horizon=10, step=1)
    assert len(scores) == len(labels) and len(scores) > 100
    assert set(labels) <= {0, 1}
    assert all(0.0 <= s <= 1.0 for s in scores)


def test_forecast_beats_half_on_self_exciting_events():
    # events generated by a genuine Hawkes -> its own intensity should rank days above
    # chance out of sample (high intensity really does precede more events)
    sys.path.insert(0, os.path.join(ROOT, "level9"))
    from hawkes import simulate
    mu, alpha, beta = 0.05, 0.12, 0.2               # branching ratio 0.6 (subcritical)
    ev = sorted(int(x) for x in simulate(mu, alpha, beta, 12000, seed=3))
    scores, labels = oos_event_forecast(ev, 12000, mu, alpha, beta,
                                        t_train=8000, horizon=10)
    assert roc_auc(scores, labels) > 0.55           # self-excitation is forecastable


def test_causal_equity_and_buyhold():
    prices = [100.0 * (1.02 ** t) for t in range(200)]       # steady up-trend
    bh = buy_hold(prices)
    eq = causal_dc_equity(prices, 0.05, cost=0.0)["wealth"]
    assert bh > 1.0
    assert eq > 0.0
