"""Causal deconvolution of graphs by generating mechanism, in the index-set calculus.

This is the graph counterpart of :mod:`causal_models`, and it completes the parallel
with the paper: every object the paper deconvolves, deconvolved by mechanism rather
than by complexity.

Why a separate module.  :mod:`causalbool_mirror` supplies an index-set *description
length* that can be dropped into the paper's Algorithms 1 and 2 in place of BDM.
That is a useful control, but it is not our method -- it is their algorithm running
on our number.  Our method asks the question the index-set calculus is actually for:

    which nodes share a generating mechanism, and what is that mechanism?

A graph produced by a short program has an index-set law.  In a complete graph every
node is joined to every index but its own; in a star every node is joined to one fixed
index; in a ``k``-ary tree node ``i`` is joined to index ``(i-1)//k``.  These are
index-set rules, they are exact, and they can be *recognised*.  A graph produced by a
pseudo-random process has no such law, and the honest answer for it is "no mechanism",
not a large number.

So the deconvolution becomes: **cut the fewest edges such that each resulting component
is exactly generated by some mechanism in the library.**  The edges cut are the ones
belonging to no mechanism -- which is precisely the set the paper's Algorithm 1 tries
to find by minimising information loss.

The library is deliberately small and closed-form.  It is not a classifier and nothing
is fitted: a component either *is* a complete graph on its nodes or it is not.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import networkx as nx

__all__ = [
    "Mechanism",
    "identify_mechanism",
    "MECHANISM_LIBRARY",
    "GraphDeconvolution",
    "deconvolve_graph",
]


@dataclass(frozen=True)
class Mechanism:
    """An exact index-set law for a component, or the absence of one."""

    name: str
    params: tuple = ()
    n_nodes: int = 0

    def describe(self) -> str:
        if self.name == "none":
            return f"no index-set law ({self.n_nodes} nodes)"
        p = ", ".join(f"{k}={v}" for k, v in self.params)
        return f"{self.name}({p}) on {self.n_nodes} nodes" if p else f"{self.name} on {self.n_nodes} nodes"

    @property
    def is_mechanism(self) -> bool:
        return self.name != "none"


# ---------------------------------------------------------------------------
# Exact recognisers.  Each answers "is this component EXACTLY this object?"
# ---------------------------------------------------------------------------


def _is_complete(H: nx.Graph) -> bool:
    n = H.number_of_nodes()
    return n >= 2 and H.number_of_edges() == n * (n - 1) // 2


def _is_star(H: nx.Graph) -> tuple[bool, int | None]:
    n = H.number_of_nodes()
    if n < 3 or H.number_of_edges() != n - 1:
        return False, None
    degs = sorted(d for _, d in H.degree())
    if degs[-1] != n - 1 or any(d != 1 for d in degs[:-1]):
        return False, None
    hub = max(H.degree(), key=lambda t: t[1])[0]
    return True, hub


def _is_path(H: nx.Graph) -> bool:
    n = H.number_of_nodes()
    if n < 3 or H.number_of_edges() != n - 1:
        return False
    degs = sorted(d for _, d in H.degree())
    return degs[0] == 1 and degs[1] == 1 and all(d == 2 for d in degs[2:])


def _is_cycle(H: nx.Graph) -> bool:
    n = H.number_of_nodes()
    return n >= 3 and H.number_of_edges() == n and all(d == 2 for _, d in H.degree())


def _is_kary_tree(H: nx.Graph) -> tuple[bool, int | None]:
    """Is ``H`` exactly the complete ``k``-ary tree on its own node count?

    The test is by isomorphism against the canonical construction, so it is
    independent of how the nodes happen to be labelled.
    """
    n = H.number_of_nodes()
    if n < 3 or H.number_of_edges() != n - 1 or not nx.is_tree(H):
        return False, None
    for k in (2, 3, 4):
        ref = nx.Graph()
        ref.add_nodes_from(range(n))
        for child in range(1, n):
            ref.add_edge((child - 1) // k, child)
        if nx.is_isomorphic(H, ref):
            return True, k
    return False, None


MECHANISM_LIBRARY = ("complete", "star", "kary_tree", "cycle", "path", "singleton")


def identify_mechanism(H: nx.Graph) -> Mechanism:
    """Return the exact index-set law generating ``H``, or ``none``."""
    n = H.number_of_nodes()
    if n <= 1:
        return Mechanism("singleton", (), n)
    if _is_complete(H):
        return Mechanism("complete", (("n", n),), n)
    ok, hub = _is_star(H)
    if ok:
        return Mechanism("star", (("hub", hub),), n)
    ok, k = _is_kary_tree(H)
    if ok:
        return Mechanism("kary_tree", (("k", k),), n)
    if _is_cycle(H):
        return Mechanism("cycle", (), n)
    if _is_path(H):
        return Mechanism("path", (), n)
    return Mechanism("none", (), n)


# ---------------------------------------------------------------------------
# Deconvolution by peeling maximal exact mechanisms
# ---------------------------------------------------------------------------


@dataclass
class Layer:
    """One generating mechanism peeled off the graph, with its cost of separation."""

    mechanism: Mechanism
    nodes: set
    internal_edges: int
    boundary_edges: int
    boundary: list[tuple[int, int]]

    @property
    def accepted(self) -> bool:
        """Is it cheaper to describe this part separately than to keep it joined?

        This is the paper's own inequality of Section 3.2 --
        ``|P(G1)| + |P(G2)| + |P(e)| > |P(G1 G2)|`` -- read in the index-set
        calculus.  A genuine separate mechanism explains many internal edges and
        costs few boundary edges to detach.  A clique that occurs by chance
        inside a dense random graph explains few and costs many, so it is
        rejected without any statistical test or threshold being fitted.
        """
        return self.boundary_edges < self.internal_edges

    def describe(self) -> str:
        verdict = "accepted" if self.accepted else "rejected"
        return (f"{self.mechanism.describe()} | internal {self.internal_edges} "
                f"edges, boundary {self.boundary_edges} -> {verdict}")


@dataclass
class GraphDeconvolution:
    graph: nx.Graph
    removed: list[tuple[int, int]] = field(default_factory=list)
    layers: list[Layer] = field(default_factory=list)
    residual: set = field(default_factory=set)

    @property
    def mechanisms(self) -> list[Mechanism]:
        return [l.mechanism for l in self.layers if l.accepted]

    @property
    def explained_nodes(self) -> int:
        return sum(len(l.nodes) for l in self.layers if l.accepted)

    def summary(self) -> dict:
        return {
            "edges_cut": len(self.removed),
            "mechanisms_found": [l.describe() for l in self.layers if l.accepted],
            "rejected": [l.describe() for l in self.layers if not l.accepted],
            "nodes_explained": self.explained_nodes,
            "nodes_total": self.graph.number_of_nodes(),
            "residual_nodes": len(self.residual),
        }


def _largest_complete(G: nx.Graph, cap: int = 200_000) -> set | None:
    best: set = set()
    for i, clique in enumerate(nx.find_cliques(G)):
        if len(clique) > len(best):
            best = set(clique)
        if i > cap:
            break
    return best if len(best) >= 3 else None


def _largest_star(G: nx.Graph) -> set | None:
    best: set = set()
    for h in G.nodes():
        leaves = [v for v in G[h] if G.degree(v) == 1]
        if len(leaves) + 1 > len(best):
            best = {h, *leaves}
    return best if len(best) >= 4 else None


def _whole_graph_law(G: nx.Graph) -> set | None:
    return set(G.nodes()) if identify_mechanism(G).is_mechanism else None


_FINDERS = (_whole_graph_law, _largest_complete, _largest_star)


def _make_layer(G: nx.Graph, nodes: set) -> Layer | None:
    H = G.subgraph(nodes)
    mech = identify_mechanism(H)
    if not mech.is_mechanism or mech.name == "singleton":
        return None
    boundary = [(min(u, v), max(u, v)) for u, v in G.edges()
                if (u in nodes) != (v in nodes)]
    return Layer(mech, set(nodes), H.number_of_edges(), len(boundary), boundary)


def deconvolve_graph(G: nx.Graph, max_layers: int = 6) -> GraphDeconvolution:
    """Peel off maximal exactly-generated components, largest mechanism first.

    At each round every recogniser in the library proposes its largest exact
    subgraph; the proposal explaining the most internal edges is taken, and it is
    accepted only if detaching it costs fewer boundary edges than it explains.
    The peeled nodes are removed and the search repeats on what is left.

    Peeling in order of explanatory power reproduces the hierarchy the paper
    describes in Fig. 3E -- "the algorithm first separates the subcomponents with
    the largest algorithmic difference, followed by other subcomponents, hence
    providing a natural hierarchy of source likelihood" -- but the ordering here
    is by mechanism size rather than by a difference of estimates.
    """
    work = G.copy()
    layers: list[Layer] = []
    removed: list[tuple[int, int]] = []

    for _ in range(max_layers):
        proposals = []
        for finder in _FINDERS:
            nodes = finder(work)
            if nodes:
                layer = _make_layer(G, nodes)
                if layer is not None:
                    proposals.append(layer)
        if not proposals:
            break
        layer = max(proposals, key=lambda l: (l.internal_edges, len(l.nodes)))
        layers.append(layer)
        if not layer.accepted:
            break
        removed.extend(layer.boundary)
        work.remove_nodes_from(layer.nodes)
        if work.number_of_nodes() < 3:
            break

    H = G.copy()
    H.remove_edges_from(removed)
    return GraphDeconvolution(H, sorted(set(removed)), layers, set(work.nodes()))
