"""Standalone export of the efficiency baseline R0 (or the one candidate E1) and its
isolated CLI acceptance (efficiency phase, R exit / Gate C export).

Owners reused, not restated: ``objective_index_export`` (component bundle,
source slices, AST audit, pinned-workspace checks), ``next_round_export.loader``
(the owner's loader with the solver import and call replaced, each replacement
asserted to occur exactly once) and ``optimization_export_validation.workspace``.
What is particular here is only the embedded solver -- ``research/
efficiency_search.py`` (R0) or ``research/efficiency_candidate.py`` (E1) -- and
the frozen cell: A4 catalog, depth-first traversal, 0.1 s optimisation.

``accept`` is the standalone acceptance the plan requires at R exit: the 142
programs of the direct corpus (public 8, regression 30, additional 100, stress
4; 277 cases), each written once to an ``inputs/`` folder of a temporary
workspace that holds only ``compiler.py``, the pinned ``machine.py``,
``score.py``, the pinned public tests and those inputs. Every program is
compiled by a FRESH ``python compiler.py`` process with an empty PYTHONPATH and
the external 20-second timeout; stdout must be exactly one JSON line, validated
by the pinned machine on every case. Input files are hashed before and after.
The pinned public tests and score run in the same workspace.

Usage::

    PYTHONPATH=.reference:. python -m research.efficiency_export --variant R0 --out DIR
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import List, Tuple

import machine

from research import efficiency_common as ec
from research import next_round_export as nre
from research import objective_index_export as oie
from research import optimization_common as oc
from research import optimization_export_validation as oev

from tests_direct import generate_programs as gp

SOLVERS = {"R0": ("research.efficiency_search", "research/efficiency_search.py"),
           "E1": ("research.efficiency_candidate", "research/efficiency_candidate.py")}
CELL = ec.BASELINE_CELL


def bundle(variant: str) -> List[dict]:
    items = [item for item in oie.bundle(None)
             if item["module"] != "research.objective_index_search"]
    name, relative = SOLVERS[variant]
    text = (oc.ROOT / relative).read_text(encoding="utf-8")
    items.append({"module": name, "kind": "whole", "file": relative, "source": text,
                  "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                  "file_sha256": oc.file_sha256(oc.ROOT / relative)})
    return items


def assemble(variant: str) -> Tuple[str, dict]:
    items = bundle(variant)
    header = [
        f'"""Standalone efficiency-phase compiler ({variant}: A4 catalog, depth-first, 0.1 s).',
        "",
        "Generated by research/efficiency_export.py from the measured sources, whose",
        "exact bytes are embedded below with their SHA256 and re-verified on start-up.",
        "Do not edit; regenerate. Standard library plus the supplied machine module only.",
        '"""',
        "",
        "import hashlib",
        "import json",
        "import sys",
        "import types",
        "",
        "import machine",
        "",
        f"EXPORT_ARM = {'cell_a4cat_dfs@' + variant!r}",
        "EXPORT_LEARNED = None",
        f"EXPORT_CATALOG = {CELL['catalog']!r}",
        f"EXPORT_TRAVERSAL = {CELL['traversal']!r}",
        f"EXPORT_OPTIMISATION_SECONDS = {ec.PRIMARY_BUDGET!r}",
        "",
        "_BUNDLE = [",
    ]
    for item in items:
        header.append(f"    ({item['module']!r}, {item['sha256']!r}, {item['source']!r}),")
    header.append("]")
    source = "\n".join(header) + "\n" + nre.loader(SOLVERS[variant][0])
    ast.parse(source)
    manifest = {"variant": variant, "catalog": CELL["catalog"], "traversal": CELL["traversal"],
                "optimisation_seconds": ec.PRIMARY_BUDGET,
                "components": [{k: v for k, v in item.items() if k != "source"}
                               for item in items],
                "generator_sha256": oc.file_sha256(Path(__file__)),
                "owner_generator_sha256": oc.file_sha256(oc.ROOT / "research"
                                                         / "objective_index_export.py"),
                "loader_owner_sha256": oc.file_sha256(oc.ROOT / "research"
                                                      / "next_round_export.py")}
    return source, manifest


def write_export(output: Path, variant: str) -> dict:
    source, manifest = assemble(variant)
    problems = oie.audit(source)
    manifest["audit_problems"] = problems
    if problems:
        raise RuntimeError("export audit failed: " + "; ".join(problems[:5]))
    if output.exists():
        raise FileExistsError(f"refusing to overwrite {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    manifest["export_sha256"] = oc.file_sha256(output)
    again, _ = assemble(variant)
    manifest["deterministic_regeneration"] = (hashlib.sha256(again.encode()).hexdigest()
                                              == manifest["export_sha256"])
    oc.write_immutable_json(output.parent / "compiler_MANIFEST.json", manifest)
    return manifest


def corpus() -> list:
    out = []
    for label, programs in (("public", gp.public_programs()),
                            ("regression", gp.regression_programs()),
                            ("additional", gp.additional_programs()),
                            ("stress", gp.stress_programs())):
        out.extend((label, program) for program in programs)
    return out


def accept(export_path: Path, out_dir: Path, run: Path, stage: str) -> dict:
    """Fresh-process CLI acceptance of one export on the 142-program corpus."""

    out_dir.mkdir(parents=True, exist_ok=True)
    tmp = oev.workspace(export_path)
    (tmp / "inputs").mkdir()
    programs = corpus()
    paths = []
    for i, (label, program) in enumerate(programs):
        path = tmp / "inputs" / f"{i:03d}_{program['name']}.json"
        path.write_text(json.dumps(program, sort_keys=True))
        paths.append((label, program, path, oc.file_sha256(path)))
    pinned = oie.pinned_checks(tmp, out_dir / "pinned")
    env = {"PATH": os.environ.get("PATH", ""), "PYTHONPATH": ""}
    rows, failures, cases = [], [], 0
    for label, program, path, digest in paths:
        if ec.cap_reached(run):
            raise RuntimeError("the 24-hour measurement cap is reached")
        started = time.perf_counter()
        try:
            proc = subprocess.run([oc.PYTHON, "compiler.py", str(path.relative_to(tmp))],
                                  cwd=str(tmp), capture_output=True, text=True,
                                  timeout=ec.EXTERNAL_SECONDS, env=env)
            stdout, stderr, code, timed_out = proc.stdout, proc.stderr, proc.returncode, False
        except subprocess.TimeoutExpired as exc:
            stdout = exc.stdout if isinstance(exc.stdout, str) else ""
            stderr = exc.stderr if isinstance(exc.stderr, str) else ""
            code, timed_out = None, True
        seconds = time.perf_counter() - started
        ec.charge(run, stage, f"{label}:{program['name']}", seconds)
        row = {"corpus": label, "name": program["name"], "exit_code": code,
               "timed_out": timed_out, "process_seconds": seconds,
               "stderr_tail": stderr[-300:], "cases": len(program["cases"])}
        try:
            if stdout.count("\n") != 1 or not stdout.endswith("\n"):
                raise ValueError("stdout is not exactly one JSON line")
            compiled = json.loads(stdout)
            cycles = machine.check_compilation(program, compiled)
            for case in program["cases"]:
                machine.check_case(program, compiled, case)
                cases += 1
            scratch = machine.scratch_footprint(program, compiled)
            row.update(cycles=cycles, scratch=scratch, J=cycles * scratch, ok=code == 0)
        except Exception as exc:  # retained as a failure, never skipped
            row.update(ok=False, error=f"{type(exc).__name__}: {exc}")
        row["input_unchanged"] = oc.file_sha256(path) == digest
        row["ok"] = row["ok"] and row["input_unchanged"] and not timed_out
        rows.append(row)
        if not row["ok"]:
            failures.append(row)
    expected_cases = sum(len(p["cases"]) for _, p, _, _ in paths)
    listing = sorted(str(p.relative_to(tmp)) for p in tmp.rglob("*")
                     if p.is_file() and "__pycache__" not in p.parts)
    report = {"export_sha256": oc.file_sha256(export_path), "programs": len(paths),
              "cases_checked": cases, "expected_cases": expected_cases,
              "failures": failures, "pinned": {k: v for k, v in pinned.items()
                                               if k != "score_stdout"},
              "workspace_files_other_than_inputs": [p for p in listing
                                                    if not p.startswith("inputs/")],
              "max_process_seconds": max(r["process_seconds"] for r in rows),
              "rows": rows}
    report["status"] = ("PASS" if paths and not failures and cases == expected_cases == 277
                        and len(paths) == 142 and pinned["pinned_tests_exit"] == 0
                        and pinned["score_exit"] == 0 and pinned["compiler_is_export"]
                        and pinned["embedded_modules_only"] and pinned["machine_is_pinned_copy"]
                        else "FAIL")
    oc.write_immutable_json(out_dir / "ACCEPTANCE.json", report)
    shutil.rmtree(tmp, ignore_errors=True)
    return report


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--variant", choices=sorted(SOLVERS), required=True)
    parser.add_argument("--out", required=True, help="a NEW directory")
    parser.add_argument("--run", default=str(ec.run_dir()))
    args = parser.parse_args(argv)
    out = Path(args.out)
    manifest = write_export(out / "compiler.py", args.variant)
    report = accept(out / "compiler.py", out / "acceptance", Path(args.run),
                    f"acceptance_{args.variant}")
    print(json.dumps({"variant": args.variant, "export_sha256": manifest["export_sha256"],
                      "deterministic": manifest["deterministic_regeneration"],
                      "status": report["status"], "programs": report["programs"],
                      "cases": report["cases_checked"], "failures": len(report["failures"])}))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
