"""Standalone export of the frozen next-round candidate, and its isolated validation.

The earlier release's owner (``objective_index_export``) does the work: its
component bundle, source-slice mechanism, loader, AST audit, pinned-workspace
checks and 3-repetition measurement are reused unchanged. What is particular to
this round is only:

- the solver embedded is the SUCCESSOR ``research/next_round_search.py`` (or,
  had it been frozen, ``research/next_round_engineered.py``), not the frozen
  ``objective_index_search``;
- ``compile_program`` calls ``multiscale_optimise`` with the frozen cell's
  ``catalog`` and ``traversal`` at the 0.1 s allowance;
- the fresh programs are this round's confirmation cohort, the public entries
  and the bootstrap/research J sets come from this round's C stages.

The loader text is the owner's, with its two solver-specific statements
replaced; each replacement is asserted to occur exactly once, so a drift in the
owner fails loudly rather than producing a silently different export.

Usage::

    PYTHONPATH=.reference:. python -m research.next_round_export --run DIR
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import shutil
from pathlib import Path
from typing import List, Tuple


from research import next_round_common as nrc
from research import objective_index_export as oie
from research import optimization_common as oc
from research import optimization_export_validation as oev

LABEL = "candidate"
SOLVERS = {None: ("research.next_round_search", "research/next_round_search.py"),
           "engineered": ("research.next_round_engineered", "research/next_round_engineered.py")}

_OLD_CALL = """    else:
        best_times, best_addresses, record = _ois.optimise(
            program, facts, times, addresses, arm=EXPORT_ARM,
            budget_seconds=EXPORT_OPTIMISATION_SECONDS)"""


def loader(module: str) -> str:
    text = oie.LOADER
    old_import = "import research.objective_index_search as _ois  # noqa: E402"
    if text.count(old_import) != 1 or text.count(_OLD_CALL) != 1:
        raise RuntimeError("the owner's loader changed; refusing to patch it")
    text = text.replace(old_import, f"import {module} as _ois  # noqa: E402")
    text = text.replace(_OLD_CALL, """    else:
        best_times, best_addresses, record = _ois.multiscale_optimise(
            program, facts, times, addresses,
            budget_seconds=EXPORT_OPTIMISATION_SECONDS, catalog=EXPORT_CATALOG,
            traversal=EXPORT_TRAVERSAL)""")
    return text


def bundle(variant) -> List[dict]:
    items = [item for item in oie.bundle(None)
             if item["module"] != "research.objective_index_search"]
    name, relative = SOLVERS[variant]
    text = (oc.ROOT / relative).read_text(encoding="utf-8")
    items.append({"module": name, "kind": "whole", "file": relative, "source": text,
                  "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                  "file_sha256": oc.file_sha256(oc.ROOT / relative)})
    return items


def assemble(arm: str) -> Tuple[str, dict]:
    parent = arm.split("+", 1)[0]
    variant = "engineered" if arm.endswith("+engineered") else None
    cell = nrc.CELLS[parent]
    items = bundle(variant)
    header = [
        '"""Standalone next-round compiler (frozen candidate, 0.1 s optimisation allowance).',
        "",
        "Generated by research/next_round_export.py from the measured sources, whose",
        "exact bytes are embedded below with their SHA256 and re-verified on start-up.",
        "Do not edit; regenerate. Standard library plus the supplied machine module only.",
        '"""',
        "",
        "import hashlib",
        "import json",
        "import sys",
        "import types",
        "",
        "import machine",
        "",
        f"EXPORT_ARM = {arm!r}",
        "EXPORT_LEARNED = None",
        f"EXPORT_CATALOG = {cell['catalog']!r}",
        f"EXPORT_TRAVERSAL = {cell['traversal']!r}",
        f"EXPORT_OPTIMISATION_SECONDS = {nrc.PRIMARY_BUDGET!r}",
        "",
        "_BUNDLE = [",
    ]
    for item in items:
        header.append(f"    ({item['module']!r}, {item['sha256']!r}, {item['source']!r}),")
    header.append("]")
    source = "\n".join(header) + "\n" + loader(SOLVERS[variant][0])
    ast.parse(source)
    manifest = {"arm": arm, "catalog": cell["catalog"], "traversal": cell["traversal"],
                "variant": variant, "optimisation_seconds": nrc.PRIMARY_BUDGET,
                "components": [{k: v for k, v in item.items() if k != "source"}
                               for item in items],
                "generator_sha256": oc.file_sha256(Path(__file__)),
                "owner_generator_sha256": oc.file_sha256(oc.ROOT / "research"
                                                         / "objective_index_export.py")}
    return source, manifest


def write_export(output: Path, arm: str) -> dict:
    source, manifest = assemble(arm)
    problems = oie.audit(source)
    manifest["audit_problems"] = problems
    if problems:
        raise RuntimeError("export audit failed: " + "; ".join(problems[:5]))
    if output.exists():
        raise FileExistsError(f"refusing to overwrite {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    manifest["export_sha256"] = oc.file_sha256(output)
    oc.write_json(output.parent / "compiler_MANIFEST.json", manifest)
    return manifest


def validate(run: Path) -> dict:
    frozen = json.loads((run / "FROZEN_SELECTION.json").read_text())
    arm = frozen["candidate"]["frozen_candidate"]
    out_dir = run / "export" / LABEL
    output = out_dir / "compiler.py"
    report: dict = {"label": LABEL, "arm": arm}
    manifest = (write_export(output, arm) if not output.exists()
                else json.loads((out_dir / "compiler_MANIFEST.json").read_text()))
    research = frozen["sources"]["research"]
    production = frozen["sources"]["production"]
    mismatched = [c["file"] for c in manifest["components"]
                  if (research.get(c["file"]) or production.get(c["file"])) != c["file_sha256"]]
    report["build"] = {"path": str(output), "sha256": oc.file_sha256(output),
                       "component_file_mismatches_vs_freeze": mismatched,
                       "generator_matches_freeze": manifest["generator_sha256"] ==
                       research.get("research/next_round_export.py"),
                       "components": manifest["components"]}
    again, _ = assemble(arm)
    report["deterministic_regeneration"] = (hashlib.sha256(again.encode()).hexdigest()
                                            == oc.file_sha256(output))
    report["audit_problems"] = oie.audit(output.read_text())
    tmp = oev.workspace(output)
    report["pinned"] = oie.pinned_checks(tmp, out_dir / "pinned")
    public = [dict(e, corpus="public") for e in json.loads(
        (run / "stages" / "C_public" / "STAGE_MANIFEST.json").read_text())["extra"]["programs"]]
    paths = {e["program_sha256"]: e["program_path"] for e in json.loads(
        (run / "CONFIRMATION_COHORT.json").read_text())["public_programs"]}
    for entry in public:
        entry["program_path"] = paths[entry["program_sha256"]]
    fresh = [dict(e, corpus="fresh") for e in
             json.loads((run / "CONFIRMATION_COHORT.json").read_text())["programs"]]
    if nrc.cap_reached(run):
        raise RuntimeError("the 24-hour measurement cap is reached; export rows not run")
    rows = oie.measure_rows(run, tmp, LABEL, public + fresh, 3)
    report["rows"] = len(rows)
    report["expected_rows"] = (len(public) + len(fresh)) * 3
    report["failed_rows"] = sum(r["failed_row"] for r in rows)
    boot, research_j = {}, {}
    for stage in ("C_confirmation", "C_public"):
        for r in oc.read_rows(run / "stages" / stage / "rows.jsonl"):
            if r["arm"] == "accepted_bootstrap" and not r["failed_row"]:
                boot[r["program_sha256"]] = r["product"]
            if r["arm"] == arm and r["budget_seconds"] == nrc.PRIMARY_BUDGET \
                    and not r["failed_row"]:
                research_j.setdefault(r["program_sha256"], set()).add(r["product"])
    above = [r["key"] for r in rows if not r["failed_row"] and
             r["product"] > boot.get(r["program_sha256"], float("inf"))]
    differs = [r["key"] for r in rows if not r["failed_row"] and
               r["product"] not in research_j.get(r["program_sha256"], set())]
    report["outputs_above_bootstrap"] = above
    report["outputs_outside_research_J_set"] = {
        "count": len(differs), "first": differs[:10],
        "note": "timing-sensitive J variation; reported, not a failure by itself"}
    serial = {}
    for r in oc.read_rows(run / "stages" / "C_public" / "rows.jsonl"):
        if r["arm"] == "serial" and not r["failed_row"]:
            serial[r["result"]["program_name"]] = (r["cycles"], r["scratch"])
    scores = []
    for rep in range(3):
        chosen = [r for r in rows if r["corpus"] == "public" and r["repetition"] == rep]
        if len(chosen) == 8 and not any(r["failed_row"] for r in chosen):
            speed = math.exp(sum(math.log(serial[r["program_name"]][0] / r["cycles"])
                                 for r in chosen) / 8)
            space = math.exp(sum(math.log(serial[r["program_name"]][1] / r["scratch"])
                                 for r in chosen) / 8)
            scores.append(math.sqrt(speed * space))
        else:
            scores.append(None)
    report["export_public_scores"] = scores
    times = sorted(r["process_seconds"] for r in rows if not r["failed_row"])
    report["process_seconds"] = {"median": times[len(times) // 2] if times else None,
                                 "p95": times[int(0.95 * (len(times) - 1))] if times else None,
                                 "max": times[-1] if times else None}
    pinned = report["pinned"]
    report["status"] = ("PASS" if report["rows"] == report["expected_rows"] == 624
                        and report["failed_rows"] == 0 and not above
                        and pinned["compiler_is_export"] and pinned["machine_is_pinned_copy"]
                        and pinned["embedded_modules_only"] and pinned["pinned_tests_exit"] == 0
                        and pinned["score_exit"] == 0 and report["deterministic_regeneration"]
                        and not mismatched and not report["audit_problems"] else "FAIL")
    oc.write_json(out_dir / "EXPORT_VALIDATION.json", report)
    shutil.rmtree(tmp, ignore_errors=True)
    return report


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", required=True)
    args = parser.parse_args(argv)
    run = Path(args.run).resolve()
    report = validate(run)
    rows = oc.read_rows(run / "export" / LABEL / "rows.jsonl")
    for row in rows:
        nrc.charge(run, "C_export", row["key"], row["process_seconds"])
    print(json.dumps({k: report[k] for k in ("status", "rows", "failed_rows",
                                             "export_public_scores")}))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
