"""Standalone exports of R0 and C1 and their fresh-process CLI rows (Stage C).

Owners reused: ``efficiency_export`` (the R0 bundle and header; R0 must reproduce
its accepted bytes exactly), ``next_round_export.loader`` (the solver import and
call replaced, each exactly once), ``objective_index_export`` (AST audit, pinned
checks), ``optimization_export_validation.workspace``. What is particular here:
the C1 bundle adds ``research.third_round_kernel`` and
``research.third_round_candidate`` to R0's bundle, and every CLI process keeps
complete raw stdout/stderr, an attempt ledger and a ledger charge.

CLI rows (``C_acceptance``: 142-program corpus x {R0, C1}, repetition 0;
``C_export``: 200 fresh + 8 public x 3 repetitions x {R0, C1}) run
``python compiler.py inputs/<file>`` in a minimal workspace (export, pinned
machine, score, public tests, inputs) with an empty PYTHONPATH, no user site and
the 20 s timeout. stdout must be exactly one JSON line validated on every case by
the pinned machine; input bytes are hashed before and after.
"""

from __future__ import annotations

import ast
import hashlib
import json
import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import List, Tuple

import machine

from research import efficiency_export as ee
from research import next_round_export as nre
from research import objective_index_export as oie
from research import optimization_common as oc
from research import optimization_export_validation as oev
from research import third_round_common as tc
from research import third_round_resume_common as rc

C1_EXTRA = (("research.third_round_kernel", "research/third_round_kernel.py"),
            ("research.third_round_candidate", "research/third_round_candidate.py"))


def assemble(variant: str) -> Tuple[str, dict]:
    if variant == "R0":
        return ee.assemble("R0")
    if variant != "C1":
        raise ValueError(variant)
    items = ee.bundle("R0")
    for name, relative in C1_EXTRA:
        text = (oc.ROOT / relative).read_text(encoding="utf-8")
        items.append({"module": name, "kind": "whole", "file": relative, "source": text,
                      "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                      "file_sha256": oc.file_sha256(oc.ROOT / relative)})
    header = [
        '"""Standalone third-round compiler (C1: A4 catalog, depth-first, 0.1 s, BS1 state).',
        "",
        "Generated by research/third_round_resume_export.py from the measured sources, whose",
        "exact bytes are embedded below with their SHA256 and re-verified on start-up.",
        "Do not edit; regenerate. Standard library plus the supplied machine module only.",
        '"""',
        "",
        "import hashlib",
        "import json",
        "import sys",
        "import types",
        "",
        "import machine",
        "",
        "EXPORT_ARM = 'cell_a4cat_dfs@C1'",
        "EXPORT_LEARNED = None",
        f"EXPORT_CATALOG = {ee.CELL['catalog']!r}",
        f"EXPORT_TRAVERSAL = {ee.CELL['traversal']!r}",
        "EXPORT_OPTIMISATION_SECONDS = 0.1",
        "",
        "_BUNDLE = [",
    ]
    for item in items:
        header.append(f"    ({item['module']!r}, {item['sha256']!r}, {item['source']!r}),")
    header.append("]")
    source = "\n".join(header) + "\n" + nre.loader("research.third_round_candidate")
    ast.parse(source)
    manifest = {"variant": "C1", "catalog": ee.CELL["catalog"], "traversal": ee.CELL["traversal"],
                "optimisation_seconds": 0.1,
                "components": [{k: v for k, v in i.items() if k != "source"} for i in items],
                "generator_sha256": oc.file_sha256(Path(__file__))}
    return source, manifest


def write_export(folder: Path, variant: str) -> dict:
    source, manifest = assemble(variant)
    problems = oie.audit(source)
    manifest["audit_problems"] = problems
    if problems:
        raise RuntimeError("export audit failed: " + "; ".join(problems[:5]))
    output = Path(folder) / "compiler.py"
    if output.exists():
        raise FileExistsError(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    manifest["export_sha256"] = oc.file_sha256(output)
    again, _ = assemble(variant)
    manifest["deterministic_regeneration"] = (hashlib.sha256(again.encode()).hexdigest()
                                              == manifest["export_sha256"])
    if variant == "R0":
        manifest["reproduces_accepted_R0_export"] = (manifest["export_sha256"]
                                                     == tc.R0_EXPORT_SHA256)
    oc.write_immutable_json(output.parent / "compiler_MANIFEST.json", manifest)
    return manifest


def corpus() -> List[Tuple[str, dict]]:
    return ee.corpus()


def pinned(export: Path, out_dir: Path) -> dict:
    tmp = oev.workspace(export)
    try:
        return oie.pinned_checks(tmp, out_dir)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def run_cli(run: Path, stage: str, specs: List[dict], exports: dict) -> dict:
    """One fresh ``python compiler.py`` per spec; complete raw streams; no retries."""

    out = Path(run) / "stages" / stage
    raw = out / "raw"
    raw.mkdir(parents=True, exist_ok=True)
    rows_path, attempts_path = out / "rows.jsonl", out / "ATTEMPTS.jsonl"
    keys = [tc.row_key(s) for s in specs]
    if len(set(keys)) != len(keys):
        raise RuntimeError(f"{stage}: duplicate keys")
    frozen = out / "EXPECTED_KEYS.json"
    if frozen.exists():
        if json.loads(frozen.read_text())["keys"] != keys:
            raise RuntimeError(f"{stage}: expected keys differ from the frozen list")
    else:
        oc.write_immutable_json(frozen, {"stage": stage, "count": len(keys), "keys": keys,
                                         "sha256": oc.object_sha256(keys)})
    done = {tc.row_key(r) for r in rc.strict_rows(rows_path)}
    tried = {r["key"] for r in rc.strict_rows(attempts_path)}
    spaces = {}
    for arm, export in exports.items():
        tmp = oev.workspace(Path(export))
        (tmp / "inputs").mkdir()
        spaces[arm] = tmp
    env = {"PATH": os.environ.get("PATH", ""), "PYTHONPATH": "", "PYTHONNOUSERSITE": "1"}
    try:
        for index, spec in enumerate(specs):
            key = tc.row_key(spec)
            if key in done:
                continue
            if key in tried:
                raise RuntimeError(f"{stage}: key {key} has an attempt but no row")
            if rc.cap_reached(run):
                raise RuntimeError("combined measurement cap reached")
            tmp = spaces[spec["arm_id"]]
            program = json.loads(Path(spec["program_path"]).read_text())
            path = tmp / "inputs" / f"{index:05d}.json"
            path.write_text(json.dumps(program, sort_keys=True))
            digest = oc.file_sha256(path)
            argv = [oc.PYTHON, "compiler.py", str(path.relative_to(tmp))]
            oc.append_row(attempts_path, {"key": key, "index": index, "argv": argv,
                                          "started_utc": _utc()})
            started = time.perf_counter()
            timed_out = False
            try:
                proc = subprocess.run(argv, cwd=str(tmp), capture_output=True,
                                      timeout=tc.EXTERNAL_SECONDS, env=env)
                code, stdout, stderr = proc.returncode, proc.stdout, proc.stderr
            except subprocess.TimeoutExpired as exc:
                timed_out, code = True, None
                stdout, stderr = exc.stdout or b"", exc.stderr or b""
            seconds = time.perf_counter() - started
            (raw / f"{index:05d}.stdout").write_bytes(stdout)
            (raw / f"{index:05d}.stderr").write_bytes(stderr)
            tc.charge(run, stage, key, seconds)
            row = {k: spec[k] for k in tc.KEY_FIELDS + ("seed",)}
            row.update(process_seconds=seconds, exit_code=code, timed_out=timed_out,
                       raw_index=index, stdout_sha256=oc.sha256_bytes(stdout),
                       stderr_sha256=oc.sha256_bytes(stderr), corpus=spec.get("corpus"),
                       export_sha256=oc.file_sha256(tmp / "compiler.py"))
            oc.append_row(attempts_path, {"key": key, "index": index, "finished_utc": _utc(),
                                          "exit_code": code, "timed_out": timed_out,
                                          "process_seconds": seconds,
                                          "stdout_sha256": row["stdout_sha256"],
                                          "stderr_sha256": row["stderr_sha256"]})
            try:
                text = stdout.decode("utf-8")
                if text.count("\n") != 1 or not text.endswith("\n"):
                    raise ValueError("stdout is not exactly one JSON line")
                compiled = json.loads(text)
                cycles = machine.check_compilation(program, compiled)
                cases = 0
                for case in program["cases"]:
                    machine.check_case(program, compiled, case)
                    cases += 1
                scratch = machine.scratch_footprint(program, compiled)
                row.update(cycles=cycles, scratch=scratch, J=cycles * scratch, cases=cases,
                           ok=(code == 0))
            except Exception as exc:        # retained as a failure, never skipped
                row.update(ok=False, error=f"{type(exc).__name__}: {exc}")
            row["input_unchanged"] = oc.file_sha256(path) == digest
            row["ok"] = bool(row["ok"] and row["input_unchanged"] and not timed_out)
            if not row["ok"]:
                row["failed"] = True
            oc.append_row(rows_path, row)
    finally:
        listing = {arm: sorted(str(p.relative_to(t)) for p in t.rglob("*") if p.is_file()
                               and "__pycache__" not in p.parts and "inputs" not in p.parts)
                   for arm, t in spaces.items()}
        oc.write_json(out / f"WORKSPACE_LISTING_{_utc().replace(':', '')}.json", listing)
        for t in spaces.values():
            shutil.rmtree(t, ignore_errors=True)
    return tc.check_rows(rc.strict_rows(rows_path), keys)


def _utc() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def main(argv=None) -> int:
    import argparse

    from research import third_round_resume_stage_c as sc
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", required=True)
    parser.add_argument("--stage", required=True, choices=("C_acceptance", "C_export"))
    args = parser.parse_args(argv)
    run = Path(args.run)
    states = json.loads((run / "STAGE_STATES.json").read_text())
    if states["gates"].get("D") != "PASS" or not (run / "CONFIRMATION_FREEZE.json").exists():
        raise RuntimeError("Stage C requires a D PASS and the confirmation freeze")
    freeze = json.loads((run / "CONFIRMATION_FREEZE.json").read_text())
    exports = {arm: info["path"] for arm, info in freeze["exports"].items()}
    for arm, info in freeze["exports"].items():
        if oc.file_sha256(Path(info["path"])) != info["sha256"]:
            raise RuntimeError(f"export {arm} differs from the freeze")
    plan = sc.specs(run, args.stage)
    if len(plan) != tc.EXPECTED_ROWS[args.stage]:
        raise RuntimeError(f"{len(plan)} specs, expected {tc.EXPECTED_ROWS[args.stage]}")
    if args.stage == "C_acceptance":
        for arm, path in exports.items():
            out = run / "stages" / "C_acceptance" / f"pinned_{arm}"
            if not out.exists():
                result = pinned(Path(path), out)
                oc.write_immutable_json(out / "PINNED.json",
                                        {k: v for k, v in result.items() if k != "score_stdout"}
                                        | {"score_stdout": result.get("score_stdout")})
    result = run_cli(run, args.stage, plan, exports)
    print(json.dumps({k: (v if not isinstance(v, list) else len(v)) for k, v in result.items()}))
    return 0 if result["complete"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
