"""The index-set method as it actually is: named gates, a network, BDM.

Phase 1b. Phase 1's B4 compared a parent set plus an arbitrary lookup table
against a conditional probability table, and lost. That was not the method — a
named gate costs a few bits where an arbitrary map over the same inputs costs
tens — so this module rebuilds the comparison with the real gate family, over a
whole network, scored algorithmically.

Three corrections, each answering a specific defect of Phase 1:

**Named gates, not arbitrary maps.** The gate catalogue is generated by calling
``apply_gate`` from ``vendor/causalbool.py``, which is the validated forward
model of the deconvolution programme (200/200 exact recovery, proven identical to
``CausalBoolCore.wl`` on 45/45 cases). Nothing is reimplemented.

**A network, not one conditional.** Every binarised node is a target as well as a
candidate parent, so the fitted object is a connectivity matrix plus a gate per
node — the same object the forward method consumes.

**BDM, not counting.** The model term is the Block Decomposition Method applied
to the model encoded as a discrete array. A counting code is blind to structure
by construction: a constant map, XOR and a random map all cost the same number of
bits. BDM is not. The counting code is retained and reported alongside so that
any disagreement between instruments is visible.

Real data will not match a gate exactly, so gates are fitted as **nearest gates**
and the mismatches are paid for by a residual code. That is the approximate-gate
extension already on the programme's roadmap, and it carries the guard agreed
there: an approximate gate must beat both the LUT description length and the
shuffle null, or it is overfitting.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from functools import lru_cache
from itertools import combinations, product

import numpy as np
import pandas as pd

from .index_set import log2, log2_binom, residual_bits, structure_bits

_VENDOR = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))), "vendor")
if _VENDOR not in sys.path:
    sys.path.insert(0, _VENDOR)

import causalbool  # noqa: E402  (vendored forward model, unmodified)
import deconvolution as _dec  # noqa: E402  (vendored gate identifier, unmodified)

#: Gates taking parameters, expanded over their parameter grid below.
_PARAMETRIC = {"KOFN", "CANALISING"}


def _regulatory_variants(arity: int) -> list:
    return [("REGULATORY", {"activators": list(acts), "arity": arity})
            for r in range(1, arity + 1)
            for acts in combinations(range(1, arity + 1), r)]


@lru_cache(maxsize=None)
def gate_catalogue(arity: int) -> tuple:
    """Every named gate of a given arity, as (name, params, truth table).

    Truth tables are produced by evaluating the vendored ``apply_gate`` over all
    2^arity inputs in the LSB-first order the forward model uses, so the
    catalogue cannot drift from the semantics it is meant to represent.
    Duplicates — distinct names realising the same function at this arity — are
    kept, because gate identity is genuinely non-unique and the programme reports
    equivalence classes rather than hiding them.
    """
    out = []
    names = list(causalbool.GATE_TYPES) + ["TRUE", "FALSE"]
    # REGULATORY (activator/inhibitor AND-NOT) and its DNF union were added to
    # the family by the deconvolution programme and were pre-declared for this
    # comparison, so they are enumerated here rather than left out. REGULATORY
    # is parameterised by which inputs act as activators; the DNF form is
    # generated from the target function itself in ``_dnf_candidate`` below.

    for name in names:
        grids = [{}]
        if name == "KOFN":
            grids = [{"k": k} for k in range(1, arity + 1)]
        elif name == "CANALISING":
            grids = [{"canalisingInput": i, "canalisingValue": v, "defaultValue": d}
                     for i in range(1, arity + 1) for v in (0, 1) for d in (0, 1)]
        for params in grids:
            try:
                table = tuple(
                    causalbool.apply_gate(name, [(x >> i) & 1 for i in range(arity)],
                                          params)
                    for x in range(2 ** arity))
            except Exception:
                continue
            out.append((name, tuple(sorted(params.items())), table))

    for name, params in _regulatory_variants(arity):
        try:
            table = tuple(
                causalbool.apply_gate(name, [(x >> i) & 1 for i in range(arity)],
                                      params)
                for x in range(2 ** arity))
        except Exception:
            continue
        out.append((name, tuple(sorted((k, tuple(v) if isinstance(v, list) else v)
                                       for k, v in params.items())), table))
    return tuple(out)


def dnf_candidate(observed_table) -> tuple | None:
    """REGULATORY_DNF fitted to a target function, when it compresses it.

    The DNF form is not a fixed member of the catalogue: it is generated from
    the function it is asked to describe, as a union of activator/inhibitor
    clauses, and is admitted only when it uses fewer clauses than the function
    has minterms. That admission rule is the falsifiability guard the
    deconvolution programme applies -- a random function needs about 14.5
    clauses where AND needs 1 -- so the form cannot fit anything.
    """
    t = list(int(v) for v in observed_table)
    if sum(t) == 0:
        return None
    try:
        clauses = _dec.minimal_dnf(t)
    except Exception:
        return None
    if not clauses or len(clauses) >= sum(t):
        return None
    return ("REGULATORY_DNF", (("clauses", len(clauses)),), tuple(t), len(clauses))


@dataclass
class NodeFit:
    """One node's fitted model, under one model class."""

    node: str
    parents: tuple[str, ...]
    gate: str
    params: dict
    table: tuple                     #: truth table over the parent patterns
    n: int
    n_errors: int
    model_bits: float
    data_bits: float

    @property
    def total(self) -> float:
        return self.model_bits + self.data_bits


def _design(frame: pd.DataFrame, target: str, columns: list[str]):
    X = frame[columns].to_numpy(np.int64)[:-1]
    y = frame[target].to_numpy(np.int64)[1:]
    return X, y


def _pattern_codes(Xs: np.ndarray) -> np.ndarray:
    codes = np.zeros(len(Xs), dtype=np.int64)
    for j in range(Xs.shape[1]):
        codes |= (Xs[:, j] << j)          # LSB-first, matching the forward model
    return codes


def fit_node_gate(frame: pd.DataFrame, target: str, columns: list[str],
                  max_indegree: int = 3, allow_lut: bool = True) -> NodeFit:
    """Nearest named gate over the best parent set, by counting code length.

    Selection is by two-part counting length here; the algorithmic length is
    computed afterwards on the assembled network, because BDM is below its
    resolution on a single node's table (3.5σ at 4×4 against 17.9σ at 8×8) and
    selecting on a statistic that cannot see structure at that scale would be
    worse than selecting on one that at least counts honestly.
    """
    X, y = _design(frame, target, columns)
    idx = {c: j for j, c in enumerate(columns)}
    n_cand = len(columns)
    best: NodeFit | None = None

    for k in range(1, max_indegree + 1):
        for parents in combinations(columns, k):
            Xs = X[:, [idx[p] for p in parents]]
            codes = _pattern_codes(Xs)
            # counts[pattern, outcome]
            counts = np.zeros((2 ** k, 2), dtype=np.int64)
            np.add.at(counts, (codes, y), 1)

            candidates = [(n, p, t, None) for n, p, t in gate_catalogue(k)]
            lut = tuple(int(counts[p, 1] >= counts[p, 0]) for p in range(2 ** k))
            if allow_lut:
                candidates.append(("LUT", (("table", lut),), lut, None))
            # The DNF form is generated from the empirical table rather than
            # enumerated, and is admitted only when it compresses it.
            dnf = dnf_candidate(lut)
            if dnf is not None:
                candidates.append(dnf)

            for name, params, table, n_clauses in candidates:
                tab = np.asarray(table, dtype=np.int64)
                errors = int(counts[np.arange(2 ** k), 1 - tab].sum())
                base = structure_bits(n_cand, k, max_indegree)
                if name == "LUT":
                    # A LUT must transmit its whole table; a named gate needs
                    # only its name and parameters.
                    model = base + 2 ** k
                elif name == "REGULATORY_DNF":
                    # Clause count, then each clause's role for each input:
                    # activator, inhibitor or absent.
                    from .index_set import elias_gamma_bits
                    model = (base + log2(len(gate_catalogue(k)) + 2)
                             + elias_gamma_bits(n_clauses)
                             + n_clauses * k * log2(3))
                else:
                    model = base + log2(len(gate_catalogue(k)) + 2)
                data = residual_bits(len(y), errors, 2)
                if best is None or model + data < best.total:
                    best = NodeFit(node=target, parents=parents, gate=name,
                                   params=dict(params) if name != "LUT" else {},
                                   table=tuple(table), n=len(y), n_errors=errors,
                                   model_bits=model, data_bits=data)
    return best


def fit_node_cpt(frame: pd.DataFrame, target: str, columns: list[str],
                 max_indegree: int = 3, prior: float = 1.0) -> NodeFit:
    """The comparison arm on the same binarised nodes: a conditional table."""
    X, y = _design(frame, target, columns)
    idx = {c: j for j, c in enumerate(columns)}
    n_cand = len(columns)
    best: NodeFit | None = None

    for k in range(1, max_indegree + 1):
        for parents in combinations(columns, k):
            Xs = X[:, [idx[p] for p in parents]]
            codes = _pattern_codes(Xs)
            counts = np.zeros((2 ** k, 2), dtype=np.int64)
            np.add.at(counts, (codes, y), 1)
            realised = counts.sum(axis=1) > 0
            probs = (counts + prior) / (counts + prior).sum(axis=1, keepdims=True)
            data = float(-(counts * np.log2(probs)).sum())
            free = int(realised.sum())          # one free parameter per pattern
            model = (structure_bits(n_cand, k, max_indegree)
                     + free * 0.5 * log2(len(y)))
            if best is None or model + data < best.total:
                best = NodeFit(node=target, parents=parents, gate="CPT",
                               params=dict(n_free=free), table=tuple(probs[:, 1]),
                               n=len(y),
                               n_errors=int(counts.sum()
                                            - counts.max(axis=1).sum()),
                               model_bits=model, data_bits=data)
    return best


def fit_network(frame: pd.DataFrame, columns: list[str], model: str = "gate",
                max_indegree: int = 3) -> list[NodeFit]:
    """Fit every node. This is the object the method actually produces."""
    fitter = {"gate": fit_node_gate, "cpt": fit_node_cpt}[model]
    return [fitter(frame, c, columns, max_indegree) for c in columns]


def connectivity_matrix(fits: list[NodeFit], columns: list[str]) -> np.ndarray:
    """``C[k, i] = 1`` iff node *i* feeds node *k*, matching the forward model."""
    idx = {c: j for j, c in enumerate(columns)}
    C = np.zeros((len(columns), len(columns)), dtype=int)
    for f in fits:
        for p in f.parents:
            C[idx[f.node], idx[p]] = 1
    return C


def truth_table_array(fits: list[NodeFit], max_indegree: int = 3) -> np.ndarray:
    """Truth tables padded to a common width, as one binary array for BDM."""
    width = 2 ** max_indegree
    rows = []
    for f in fits:
        t = list(f.table)
        if f.gate == "CPT":
            t = [int(v >= 0.5) for v in t]      # the table's own decision rule
        t = (t * width)[:width] if t else [0] * width
        rows.append(t)
    return np.asarray(rows, dtype=int)


def parameter_array(fits: list[NodeFit], max_indegree: int = 3,
                    n_levels_bits: int = 4) -> np.ndarray:
    """CPT probabilities quantised to a fixed precision, as bits, for BDM.

    Quantisation is what lets BDM be applied to both sides: without it the
    instrument would face a discrete object on one side and a continuous one on
    the other. The precision is fixed in advance and reported.
    """
    width = 2 ** max_indegree
    rows = []
    for f in fits:
        t = list(f.table)
        t = (t * width)[:width] if t else [0.5] * width
        bits = []
        for v in t:
            q = int(round(float(v) * (2 ** n_levels_bits - 1)))
            bits.extend((q >> b) & 1 for b in range(n_levels_bits))
        rows.append(bits)
    return np.asarray(rows, dtype=int)
