#!/usr/bin/env python3
"""AUDIT03/R3 — benchmark of D_schema, the single schema-normal-form description length.

Requested by the author before deciding whether it replaces D_formula = 135.66.

D_schema charges, for a node written as a list of schemata over n coordinates:

    Elias-gamma(number of schemata)
    per schema:  log2(n+1)      its ORDER k, how many coordinates it fixes
                 log2 C(n,k)    which coordinates those are
                 k              their values, one bit each

Nothing else is transmitted. The don't-care fillings -- the sumandos -- are
REGENERATED by the decoder, which is the whole point of the method. No gate
catalogue is consulted, so the measure applies to every node whether or not its
shape has ever been named.

Three arms:
  B1  the 10-node flagship, where D_formula = 135.66 is published;
  B2  DECODABILITY: the schemata must regenerate the exact one-set, elementwise;
  B3  the biological corpus, with coverage reported honestly rather than assumed.

Run:
    venv/bin/python audit/AUDIT03_R3_description_length/bench_schema_normal_form.py
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "index-deconvolution" / "src"))
sys.path.insert(0, str(ROOT / "papers" / "method" / "code" / "complexity_analysis"))

from deconvolution import minimal_dnf                        # noqa: E402
from complexity_analysis import _eval_gate, encode_node_cost  # noqa: E402

LINE = "-" * 78
GATE12 = ["AND", "OR", "XOR", "NAND", "NOR", "XNOR", "NOT", "IMPLIES",
          "NIMPLIES", "MAJORITY", "KOFN", "CANALISING"]

CM10 = [
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
]
DYN10 = ["AND", "OR", "XOR", "KOFN", "NOR", "XNOR", "NOT",
         "IMPLIES", "NIMPLIES", "MAJORITY"]
PARAMS10 = {4: {"k": 2}, 8: {"pair": [1, 9]}, 9: {"pair": [2, 10]}}


def part(t):
    print(f"\n{LINE}\n{t}\n{LINE}")


def _log2(x):
    return math.log2(x) if x > 0 else 0.0


def gamma_len(x: int) -> int:
    return 2 * (x.bit_length() - 1) + 1


def local_tt(gate, d, params=None):
    return [_eval_gate(gate, [(y >> i) & 1 for i in range(d)], params or {})
            for y in range(2 ** d)]


def schemata_global(tt, ic, n):
    """Lift the local schemata onto the n ambient coordinates.

    A clause fixes some of the node's OWN inputs; the coordinates it leaves
    free -- whether they are among the connected inputs or not -- are the
    sumandos of that schema. Returns (fixed_coord, value) lists, 0-based on n.
    """
    out = []
    for c in minimal_dnf(tt):
        fixed = [(ic[a], 1) for a in c["activators"]] + \
                [(ic[b], 0) for b in c["inhibitors"]]
        out.append(sorted(fixed))
    return out


def d_schema(schemata, n) -> float:
    if not schemata:
        return float(gamma_len(1))
    bits = float(gamma_len(len(schemata) + 1))
    for s in schemata:
        k = len(s)
        bits += _log2(n + 1) + _log2(math.comb(n, k)) + k
    return bits


def regenerate(schemata, n):
    """Decoder side: expand every schema over ALL fillings of its don't-cares.
    This is Dec(L, Omega) in its general form -- the sumandos are rebuilt here,
    never transmitted."""
    out = set()
    for s in schemata:
        fixedbits = {c: v for c, v in s}
        free = [i for i in range(n) if i not in fixedbits]
        base = sum(v << c for c, v in s)
        for m in range(2 ** len(free)):
            idx = base
            for t, c in enumerate(free):
                if (m >> t) & 1:
                    idx |= (1 << c)
            out.add(idx + 1)
    return sorted(out)


# ===========================================================================
part("B1 — the 10-node flagship: D_formula versus D_schema, per node")
# ===========================================================================
n = 10
rows, tot_f, tot_s = [], 0.0, 0.0
print(f"  {'node':>4} {'gate':<10}{'d':>3}{'|on-set|':>10}{'schemata':>10}"
      f"{'D_formula':>12}{'D_schema':>11}")
for k in range(n):
    ic = [j for j, v in enumerate(CM10[k]) if v == 1]
    tt = local_tt(DYN10[k], len(ic), PARAMS10.get(k + 1))
    sch = schemata_global(tt, ic, n)
    onesz = sum(tt) * 2 ** (n - len(ic))
    f = encode_node_cost(len(ic), DYN10[k], n)
    s = d_schema(sch, n)
    tot_f += f
    tot_s += s
    rows.append(dict(node=k + 1, gate=DYN10[k], d=len(ic), onesz=onesz,
                     schemata=len(sch), D_formula=f, D_schema=s))
    print(f"  {k + 1:>4} {DYN10[k]:<10}{len(ic):>3}{onesz:>10}{len(sch):>10}"
          f"{f:>12.2f}{s:>11.2f}")
print(f"  {'TOTAL':>28}{sum(r['onesz'] for r in rows):>10}"
      f"{sum(r['schemata'] for r in rows):>10}{tot_f:>12.2f}{tot_s:>11.2f}")
print(f"""
  D_formula = {tot_f:.2f} bits   (the published 135.66, reproduced)
  D_schema  = {tot_s:.2f} bits   ({tot_s / tot_f:.2f}x)

  The whole network's behaviour is {sum(r['onesz'] for r in rows)} one-indices,
  generated by {sum(r['schemata'] for r in rows)} schemata. D_schema is larger than
  D_formula because it buys no dictionary: it never says "gate number 3", it
  writes the templates out. XOR is where the gap opens, exactly as expected --
  its minterms do not merge, so it needs one schema per minterm.""")


# ===========================================================================
part("B2 — DECODABILITY: do the schemata regenerate the exact one-set?")
# ===========================================================================
print("""
  A length is only a description length if a decoder can rebuild the object.
  Regenerate every node's one-set from its schemata alone -- expanding the
  don't-cares, which is the general Dec(L, Omega) -- and compare ELEMENTWISE
  against exhaustive evaluation.
""")
allok = True
print(f"  {'node':>4} {'gate':<10}{'|regenerated|':>15}{'|exhaustive|':>14}  identical?")
for k in range(n):
    ic = [j for j, v in enumerate(CM10[k]) if v == 1]
    tt = local_tt(DYN10[k], len(ic), PARAMS10.get(k + 1))
    got = regenerate(schemata_global(tt, ic, n), n)
    want = sorted(idx + 1 for idx in range(2 ** n)
                  if _eval_gate(DYN10[k],
                                [(idx >> j) & 1 for j in ic],
                                PARAMS10.get(k + 1, {})) == 1)
    ok = got == want
    allok &= ok
    print(f"  {k + 1:>4} {DYN10[k]:<10}{len(got):>15}{len(want):>14}  "
          f"{'YES' if ok else 'NO'}")
print(f"\n  all ten regenerate exactly: {allok}")


# ===========================================================================
part("B3 — the biological corpus, with coverage stated not assumed")
# ===========================================================================
from integration.bio_D_experiment import load_processed_bio_networks   # noqa: E402

nets = load_processed_bio_networks(ROOT)
cov = {"named": 0, "unnamed": 0, "skipped_high_degree": 0}
sum_f = sum_s = 0.0
by_d = {}
for nm, v in nets.items():
    nn = len(v["dynamic"])
    if nn == 0:
        continue
    for i, g in enumerate(v["dynamic"]):
        d = int(sum(v["cm"][i]))
        if g not in GATE12:
            cov["unnamed"] += 1
            continue
        if d > 12:
            cov["skipped_high_degree"] += 1
            continue
        cov["named"] += 1
        ic = [j for j, w in enumerate(v["cm"][i]) if w == 1]
        tt = local_tt(g, d)
        sch = schemata_global(tt, ic, nn)
        f = encode_node_cost(d, g, nn)
        s = d_schema(sch, nn)
        sum_f += f
        sum_s += s
        b = by_d.setdefault(d, [0, 0.0, 0.0, 0])
        b[0] += 1
        b[1] += f
        b[2] += s
        b[3] += len(sch)
print(f"""
  Coverage. D_schema needs a local truth table. It is derivable here only for
  nodes carrying one of the twelve labels: {cov['named']} nodes.
  {cov['unnamed']} nodes are CUSTOM / IDENTITY / INPUT and their formulas are
  multi-valued threshold expressions (GEQ/LT over theta), recorded unevaluable
  by construction in AUDIT02/H. They are NOT silently skipped -- they are the
  open item, and they are what R4 exists to reach.
""")
print(f"  {'d':>3}{'nodes':>8}{'schemata/node':>15}{'D_formula':>12}{'D_schema':>11}"
      f"{'ratio':>8}")
for d in sorted(by_d):
    c, f, s, sc = by_d[d]
    print(f"  {d:>3}{c:>8}{sc / c:>15.2f}{f / c:>12.2f}{s / c:>11.2f}"
          f"{s / f:>8.2f}x")
print(f"\n  totals over the {cov['named']} covered nodes: "
      f"D_formula {sum_f:.1f} bits, D_schema {sum_s:.1f} bits "
      f"({sum_s / sum_f:.2f}x)")

json.dump({"benchmark10": {"rows": rows, "D_formula": tot_f, "D_schema": tot_s,
                           "regenerates_exactly": allok},
           "corpus": {"coverage": cov, "D_formula": sum_f, "D_schema": sum_s,
                      "by_indegree": {str(k): v for k, v in sorted(by_d.items())}}},
          open(HERE / "schema_benchmark.json", "w"), indent=1)


part("READING")
print(f"""
  1. D_schema is a real description length: it regenerates every one-set
     exactly ({allok}), and its schema field's Kraft sum is exactly 1 over the
     3^n template alphabet (checked in probe_sumandos_two_readings.py).

  2. It is {tot_s / tot_f:.2f}x larger than D_formula on the flagship and
     {sum_s / sum_f:.2f}x larger on the covered corpus. That is the price of
     honesty, not a defect: D_formula charges log2(12) for a dictionary that was
     never transmitted.

  3. It ranks gates differently, and correctly. Under D_formula an XOR and an OR
     of the same in-degree cost the SAME, because both are one entry in the
     catalogue. Under D_schema the OR is cheap and the XOR expensive, because
     the OR's minterms merge into few templates and the XOR's merge into none.
     A measure that cannot tell those two apart is not measuring the object.

  4. The open question is not the formula but the COVERAGE: {cov['unnamed']} of
     {cov['named'] + cov['unnamed']} corpus nodes have no derivable Boolean truth
     table at all, because their formulas are multi-valued. No description
     length of any kind reaches them until that is resolved.
""")
