(* Whole ordered output-repertoire owner.

   The input repertoire is implicit and ordered as decimal states 0..2^N-1.
   We represent the complete output matrix column by column.  For each output
   node, IndexSetAnalytic returns the exact one-set of implicit input-row
   indices; the pair is factored into DecimalRepertoire anchors plus the
   Sumandos offset family generated by free coordinates.  No full output
   pattern is enumerated by the production path.
*)
repo = If[StringLength[Environment["CB_REPO"]] > 0, Environment["CB_REPO"], Directory[]];
SetDirectory[repo];
inputPath = Environment["DOPPEL_INPUT_JSON"];
If[StringLength[inputPath] == 0,
  Print[ExportString[<|"error" -> "missing DOPPEL_INPUT_JSON"|>, "RawJSON"]]; Exit[2]
];

payload = Import[inputPath, "RawJSON"];
cm = payload["cm"];
dyn = payload["dyn"];
params = Lookup[payload, "params", <||>];
validateExhaustive = TrueQ[Lookup[payload, "validate_exhaustive", False]];
n = Length[cm];
limit = 2^n;

Get["src/Packages/Integration/Gates.m"];
If[validateExhaustive, Get["src/Packages/Integration/Experiments.m"]];

subsetOffsets[free_List] := If[free === {}, {0},
  Sort[DeleteDuplicates[Total /@ (Tuples[{0, 1}, Length[free]] . (2^(free - 1)) )]]
];

columnRepresentation[node_Integer] := Module[
  {connected, free, mask, oneBased, oneSet, offsets, decimals, unfolded, gate, p},
  connected = Flatten[Position[cm[[node]], 1]];
  free = Complement[Range[n], connected];
  mask = If[free === {}, 0, Total[2^(free - 1)]];
  gate = dyn[[node]];
  p = If[AssociationQ[params], Lookup[params, ToString[node], Lookup[params, node, <||>]], <||>];
  oneBased = Integration`Gates`IndexSetAnalytic[n, connected, gate, p];
  If[oneBased === $Failed,
    Return[<|"node" -> node - 1, "gate" -> gate, "connected_inputs" -> (connected - 1),
      "DecimalRepertoire" -> {}, "Sumandos" -> {}, "one_count" -> Null,
      "pair_is_disjoint" -> False, "error" -> "IndexSetAnalytic failed"|>]
  ];
  oneSet = Sort[DeleteDuplicates[oneBased - 1]];
  offsets = subsetOffsets[free];
  decimals = Select[oneSet, BitAnd[#, mask] == 0 &];
  unfolded = Sort[DeleteDuplicates[Flatten[Table[d + s, {d, decimals}, {s, offsets}]]]];
  <|"node" -> node - 1, "gate" -> gate,
    "connected_inputs" -> (connected - 1), "free_inputs" -> (free - 1),
    "DecimalRepertoire" -> decimals, "Sumandos" -> offsets,
    "one_count" -> Length[oneSet],
    "pair_is_disjoint" -> (unfolded === oneSet),
    "unfolded_count" -> Length[unfolded]|>
];

rows = Table[columnRepresentation[node], {node, 1, n}];
pairChecks = TrueQ[# ["pair_is_disjoint"]] & /@ rows;
analyticValid = And @@ pairChecks && AllTrue[rows, IntegerQ[# ["one_count"]] &];

expectedRows = If[validateExhaustive,
  dispatch = Integration`Experiments`CreateRepertoiresDispatch[cm, dyn, params];
  outputs = dispatch["RepertoireOutputs"];
  Table[Flatten[Position[outputs[[All, node]], 1]] - 1, {node, 1, n}],
  {}
];
actualRows = Table[
  Sort[DeleteDuplicates[Flatten[Table[d + s,
    {d, rows[[node]]["DecimalRepertoire"]},
    {s, rows[[node]]["Sumandos"]}]]]],
  {node, 1, n}
];
exactMatch = analyticValid && If[validateExhaustive,
  And @@ MapThread[#1 === #2 &, {expectedRows, actualRows}], True];

Print[ExportString[<|
  "network" -> <|"n" -> n, "cm" -> cm, "dyn" -> dyn, "params" -> params|>,
  "input_enumeration" -> "implicit_decimal_0_to_2^N-1",
  "output_bit_order" -> "LSB_first_node_0_to_N_minus_1",
  "representation_scope" -> "whole_ordered_output_repertoire_by_output_column",
  "production_owner" -> "Integration`Gates`IndexSetAnalytic",
  "full_output_pattern_enumeration" -> False,
  "validate_exhaustive" -> validateExhaustive,
  "column_representations" -> rows,
  "validation" -> <|"analytic_pairs_valid" -> analyticValid,
    "exact_match" -> exactMatch, "pair_checks" -> pairChecks,
    "expected_columns" -> If[validateExhaustive, Length[expectedRows], Null],
    "reconstructed_columns" -> Length[actualRows]|>
|>, "RawJSON"]];
