"""The sumandos are NOT "the disconnected coordinates". Guarded, because prose lost.

GOVERNANCE/GLOSSARY.md sec.1d, author ruling 2026-09-03:

    Definition. The sumandos of a schema are the fillings of ITS OWN DON'T-CARE
    POSITIONS, wherever those positions fall. Omega is the offset family they
    generate.

    Permitted: "the disconnected coordinates are free in every schema, and are
    the special case always present."
    FORBIDDEN: anything of the form "the sumandos are / correspond to / are
    generated by the coordinates that do not feed the node", stated as the
    definition.

WHY THIS IS A TEST AND NOT A PARAGRAPH.

The glossary records that this was settled and re-adopted FOUR times, each
recurrence costing a long conversation. It recurred a FIFTH time on 2026-09-07,
in a session whose whole subject was auditing this repository -- and the wrong
reading was sitting in the docstring of the method's OWNER
(index-deconvolution/src/deconvolution.py) the entire time, saying "the
remaining bits are the FREE COORDINATES; their subset sums are the sumandos".

A ruling that lives only in prose is re-litigated whenever someone reads the
code instead of the glossary. The cause is always the same and the glossary
names it: a reader meets a helper computing Complement[Range[n], connected] and
promotes that implementation detail into the definition. So the definition gets
a gate.

ARM 1 is executable: Rule 110 is the standing counterexample, and it either
behaves as the ruling says or it does not.

ARM 2 is a text scan over the trees this repository owns, for the forbidden
phrasing. It is not a substitute for arm 1 -- it is what stops the sentence
being written again.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
for _p in (str(ROOT / "index-deconvolution" / "src"), str(ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)


# ---------------------------------------------------------------------------
# ARM 1 — Rule 110, the standing counterexample
# ---------------------------------------------------------------------------

def _rule110_column() -> list[int]:
    """Rule 110 as a truth table over 3 inputs, LSB-first (left, centre, right).

    Wolfram numbering: the output for neighbourhood (l, c, r) read as the binary
    number lcr is bit (4l + 2c + r) of 110. Written out rather than imported so
    this test does not depend on the module it is guarding.
    """
    col = []
    for x in range(8):
        left = (x >> 2) & 1
        centre = (x >> 1) & 1
        right = x & 1
        col.append((110 >> (4 * left + 2 * centre + right)) & 1)
    return col


def test_rule110_has_no_free_coordinates_yet_does_compress():
    """The whole ruling in one case.

    All three inputs are connected, so the free coordinates are EMPTY. Under the
    forbidden reading Omega = {0}: no sumandos, no compression, and L must list
    every minterm. Under the correct reading Rule 110 is a small number of
    schemata whose don't-cares sit ON CONNECTED INPUTS.

    If the count of schemata ever equals the count of minterms, the compression
    has vanished and the forbidden reading has silently won.
    """
    from deconvolution import essential_variables, minimal_dnf, reduce_column

    col = _rule110_column()
    n = 3
    ess = essential_variables(col, n)
    assert ess == [0, 1, 2], (
        f"Rule 110 must depend on all three inputs; got {ess}. If this fails the "
        "counterexample is broken, not the ruling.")

    free = [i for i in range(n) if i not in set(ess)]
    assert free == [], "Rule 110 has NO free coordinates -- that is the point"

    reduced = reduce_column(col, n, ess)
    minterms = sum(reduced)
    schemata = minimal_dnf(reduced)

    assert minterms == 5, f"Rule 110 has five minterms; got {minterms}"
    assert len(schemata) < minterms, (
        f"Rule 110 compressed to {len(schemata)} schemata from {minterms} "
        f"minterms. With NO free coordinates, every bit of that compression "
        f"comes from don't-cares on CONNECTED inputs -- which the reading "
        f"'sumandos = disconnected coordinates' cannot express at all.")

    # And the don't-cares really are on connected inputs.
    dont_cares = [n - len(s["activators"]) - len(s["inhibitors"]) for s in schemata]
    assert any(d > 0 for d in dont_cares), (
        "no schema has a don't-care, so there is nothing for the sumandos to "
        "fill and the counterexample has stopped counter-exemplifying")


def test_or_and_xor_of_equal_in_degree_are_separated():
    """The quantitative half of the ruling (GLOSSARY sec.1d).

    The narrow reading sees compression only from disconnected coordinates, so
    it cannot tell an OR from an XOR of the same in-degree -- both are "one gate
    with n-d free coordinates". The general reading separates them exactly.

    Uses in-degree 6 rather than the glossary's 10 to keep the test quick; the
    property is the same and the numbers are recomputed here, not quoted.
    """
    from deconvolution import minimal_dnf

    d = 6
    or_col = [1 if x != 0 else 0 for x in range(2 ** d)]
    xor_col = [bin(x).count("1") % 2 for x in range(2 ** d)]

    or_schemata = len(minimal_dnf(or_col))
    xor_schemata = len(minimal_dnf(xor_col))
    xor_minterms = sum(xor_col)

    assert or_schemata == d, (
        f"an OR of in-degree {d} covers {sum(or_col)} minterms with {d} "
        f"schemata; got {or_schemata}")
    assert xor_schemata == xor_minterms, (
        f"an XOR of in-degree {d} has no mergeable minterms, so it needs one "
        f"schema each: expected {xor_minterms}, got {xor_schemata}")
    assert or_schemata != xor_schemata, (
        "OR and XOR of the same in-degree got the same schema count, so the "
        "measure has collapsed to the narrow reading and is blind to the "
        "distinction the general one makes")


# ---------------------------------------------------------------------------
# ARM 2 — the sentence must not be written again
# ---------------------------------------------------------------------------

FORBIDDEN = re.compile(
    r"sumandos?\s+(?:are|is|=|:)?\s*(?:the\s+)?(?:disconnected|unconnected)\b"
    r"|(?:disconnected|unconnected)\s+(?:nodes?|coordinates?|inputs?|bits?)\s+"
    r"(?:are|as|=)\s+(?:the\s+)?sumandos?"
    r"|their\s+subset\s+sums\s+are\s+the\s+sumandos"
    r"|free\s+coordinates?['’]?s?\s+(?:decimal\s+)?encoding\s+is\s+the\s+.?sumandos"
    r"|sumandos?\s*\(\s*the\s+free\s+(?:offset\s+)?dimension\s*\)",
    re.IGNORECASE)

# Trees this repository owns. Replication packages and provenance archives are
# excluded: imp-pathinfo's published tables and the doc/ chat transcripts are
# records of what was written at the time, and rewriting a record is not a fix.
OWNED = ("src", "index-deconvolution/src", "index-deconvolution/level3",
         "index-deconvolution/experiments", "tools", "tests")

# Declared exceptions: text that QUOTES the forbidden phrasing in order to
# forbid it. Each must actually be doing that.
QUOTING_THE_ERROR = {
    "tests/analysis/test_sumandos_definition.py",
    "index-deconvolution/src/deconvolution.py",
    "index-deconvolution/level3/behaviour_table.py",
    "index-deconvolution/experiments/exp01_pivots_sumandos.py",
}


# Extensions, not just .py. The first plant of this guard was written into a
# .sh file and slipped straight through, which is the comfortable-denominator
# failure in miniature: a scan that covers one file type reports clean over the
# types it cannot see.
SCANNED_SUFFIXES = (".py", ".m", ".wl", ".sh", ".md")


def _owned_files() -> list[Path]:
    out: list[Path] = []
    for d in OWNED:
        base = ROOT / d
        if not base.is_dir():
            continue
        for p in base.rglob("*"):
            if p.is_file() and p.suffix in SCANNED_SUFFIXES \
                    and "__pycache__" not in p.parts:
                out.append(p)
    return out


def test_the_forbidden_definition_is_not_written_anywhere_we_own():
    files = _owned_files()
    assert files, "REFUSED: scanned 0 files"
    offenders = []
    for p in files:
        rel = str(p.relative_to(ROOT))
        if rel in QUOTING_THE_ERROR:
            continue
        for i, line in enumerate(p.read_text(errors="replace").splitlines(), 1):
            if FORBIDDEN.search(line):
                offenders.append(f"{rel}:{i}: {line.strip()[:100]}")
    assert not offenders, (
        f"the forbidden definition of `sumandos` is written in {len(offenders)} "
        f"place(s), over {len(files)} files scanned:\n  " + "\n  ".join(offenders) +
        "\n\nGLOSSARY sec.1d: the sumandos of a schema are the fillings of its "
        "OWN don't-care positions, wherever they fall. The disconnected "
        "coordinates are the special case, and may be illustrated but never "
        "defined as the general object."
    )


# ---------------------------------------------------------------------------
# ARM 3 — *pivot* is a finance term (GLOSSARY sec.1e, author ruling 2026-09-07)
# ---------------------------------------------------------------------------
#
# This is a FORWARDER, not a second scanner. The owner of the terminology
# conformance concept already exists -- tools/check_glossary_conformance.sh --
# and it already scans both languages, carries the exception ledger, prints its
# denominator and refuses on zero. Re-implementing that scan here would be the
# one-concept-many-homes defect this audit removes; the shell script runs in the
# closure, and this makes it run in pytest as well.
#
# The owner had the very defect it exists to catch: until 2026-09-07 its header
# read that "pivot" in its financial sense "is confined to the
# index-deconvolution and imp-prices programmes, which are excluded below", and
# its scope was two Wolfram directories. The Python side of the Boolean method
# lives in index-deconvolution, so the guard exempted by name the tree that
# still held the defect, and reported clean.

def test_the_conformance_owner_is_green():
    import subprocess
    proc = subprocess.run(["zsh", str(ROOT / "tools" / "check_glossary_conformance.sh")],
                          capture_output=True, text=True, cwd=str(ROOT))
    assert proc.returncode == 0, (
        "tools/check_glossary_conformance.sh is not green. It owns GLOSSARY "
        "sec.1d and sec.1e for both languages.\n" + proc.stdout + proc.stderr)
    # It must print its denominator, because a scan that says "clean" over zero
    # files is the failure this audit keeps removing.
    assert "over " in proc.stdout and "files in the method trees" in proc.stdout, (
        "the conformance owner reported clean without printing its "
        "denominator:\n" + proc.stdout)


def test_the_method_vocabulary_is_the_six_names():
    """The positive statement, so the guard cannot push people into saying nothing.

    GLOSSARY sec.1e replaces one banned word with six precise ones. A guard that
    only forbids leaves a writer with no vocabulary, and the way this confusion
    survived five settlements was people reaching for the nearest available word.
    """
    six = {"connected inputs", "essential variables", "decimal anchor",
           "decimal family", "free coordinates", "sumandos"}
    glossary = (ROOT / "GOVERNANCE" / "GLOSSARY.md").read_text().lower()
    missing = {name for name in six if name not in glossary}
    assert not missing, f"GLOSSARY does not define {missing}; sec.1e names all six"


@pytest.mark.parametrize("text,should_fire", [
    ("their subset sums are the sumandos", True),
    ("the sumandos are the disconnected coordinates", True),
    ("disconnected nodes as sumandos", True),
    ("sumandos (the free offset dimension)", True),
    ("the sumandos of a schema are the fillings of its own don't-care positions", False),
    ("the disconnected coordinates are free in every schema, the special case", False),
    ("free coordinates are the complement of the essential variables", False),
])
def test_arm2_control(text, should_fire):
    """CONTROL. The permitted phrasing from the ruling must NOT fire.

    A detector that also rejects the correct sentence would push people back to
    saying nothing, which is how the definition got lost the first time.
    """
    assert bool(FORBIDDEN.search(text)) is should_fire, text
