#!/usr/bin/env zsh
# AUDIT03 — every Wolfram file under tests/MUnit must be CLASSIFIED.
#
# The defect this closes: the runner discovered tests with the glob `*Tests.m`,
# so 23 of 78 files were never executed and nobody knew. Ten of them were real
# conditional checks. A file that is neither collected nor declared missing is
# invisible, and invisible files rot -- one of them (TSK-ALGO-003) had been left
# syntactically broken by an earlier collapse in this very audit, and nothing
# went red.
#
# So membership is declared in tests/MUnit/MANIFEST.tsv and this asserts the
# declaration is complete and honest:
#
#   * every .m in the tree appears exactly once in the manifest
#   * every manifest path exists on disk
#   * every kind is one of test / quarantine / producer
#   * quarantine and producer entries carry a reason
#
#   exit 0  the manifest accounts for every file
#   exit 1  something is unclassified, missing, or unexplained
#   exit 2  refused: nothing to check
set -u
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO" || exit 1
MANIFEST="tests/MUnit/MANIFEST.tsv"

[[ -f "$MANIFEST" ]] || { echo "TEST-MANIFEST: REFUSED  $MANIFEST is missing"; exit 2; }

# AUDIT03-B: the scan covers the WHOLE tests/ tree, not just tests/MUnit.
# Restricting it to MUnit is how tests/SelfTest.m, tests/MasterRunner.m and the
# two tests/Nature Level-3 tests stayed invisible -- an entire second suite,
# with its own runner, that no command in the repository invoked.
on_disk=$(find tests -type f -name '*.m' ! -name 'RunTests.m' | sed 's|^\./||' | sort)
n_disk=$(printf '%s\n' "$on_disk" | grep -c . || true)
if [[ "$n_disk" -eq 0 ]]; then
  echo "TEST-MANIFEST: REFUSED  found 0 .m files under tests/."
  echo "  A pass over zero files is not a pass."
  exit 2
fi

STATUS=0

declared=$(grep -v '^[[:space:]]*#' "$MANIFEST" | grep -v '^[[:space:]]*$' | cut -f2 | sort)
n_decl=$(printf '%s\n' "$declared" | grep -c . || true)

# 1. unclassified files
missing_from_manifest=$(comm -23 <(printf '%s\n' "$on_disk") <(printf '%s\n' "$declared"))
if [[ -n "$missing_from_manifest" ]]; then
  echo "TEST-MANIFEST: FAIL  these files are NOT classified:"
  printf '  %s\n' ${(f)missing_from_manifest}
  echo "  -> add each to $MANIFEST as test / quarantine / producer, with a reason"
  STATUS=1
fi

# 2. manifest entries with no file
ghosts=$(comm -13 <(printf '%s\n' "$on_disk") <(printf '%s\n' "$declared"))
if [[ -n "$ghosts" ]]; then
  echo "TEST-MANIFEST: FAIL  these manifest entries have no file on disk:"
  printf '  %s\n' ${(f)ghosts}
  STATUS=1
fi

# 3. duplicates
dupes=$(printf '%s\n' "$declared" | uniq -d)
if [[ -n "$dupes" ]]; then
  echo "TEST-MANIFEST: FAIL  declared more than once:"
  printf '  %s\n' ${(f)dupes}
  STATUS=1
fi

# 4. kinds and reasons
while IFS=$'\t' read -r kind entry reason; do
  [[ -z "$kind" || "$kind" == \#* ]] && continue
  case "$kind" in
    test) ;;
    quarantine|producer)
      if [[ -z "${reason// /}" ]]; then
        echo "TEST-MANIFEST: FAIL  $entry is '$kind' with no reason given"
        STATUS=1
      fi;;
    *)
      echo "TEST-MANIFEST: FAIL  $entry has unknown kind '$kind'"
      STATUS=1;;
  esac
done < "$MANIFEST"
# NOTE: the loop variable is `entry`, never `path`. zsh TIES the array `path`
# to $PATH, so `read -r kind path` silently destroys PATH for the rest of the
# script and every later command becomes "command not found".

n_test=$(awk -F'\t' '$1=="test"{c++} END{print c+0}' "$MANIFEST")
n_quar=$(awk -F'\t' '$1=="quarantine"{c++} END{print c+0}' "$MANIFEST")
n_prod=$(awk -F'\t' '$1=="producer"{c++} END{print c+0}' "$MANIFEST")

echo "TEST-MANIFEST: ${n_decl}/${n_disk} files classified — ${n_test} test, ${n_quar} quarantine, ${n_prod} producer"
if [[ "$n_quar" -gt 0 ]]; then
  echo "TEST-MANIFEST: note — ${n_quar} quarantined file(s) export a literal status and cannot fail."
  echo "  They are excluded ON PURPOSE. Give one a predicate to promote it to 'test'."
fi

# ------------------------------------------------------------------
# AUDIT04 — the manifest was CLASSIFICATION-only, which is half the honesty.
#
# Declaring 72 tests does not mean 72 tests RAN, and nothing compared the two.
# Both halves of that gap were live in this repository at once, and both were
# found by hand rather than by a gate:
#
#   1. The tracked rollup read OK=69 FAIL=0 TOTAL=69 against a manifest
#      declaring 72. Three tests added in Phase A (TSK-ARCH-005, TSK-ARCH-006,
#      TSK-BIO-METRICS-002) were never counted, because the rollup had not been
#      regenerated by a full run since. A suite can shrink by three and the
#      number still looks like a pass.
#
#   2. results/tests/arch6/Status.txt was committed reading FAIL while that same
#      rollup read FAIL=0. The commit message for f2c2f77 states "OK on restore",
#      and the full run of 2026-09-06 confirms the test does pass -- so the CLAIM
#      was true and the ARTEFACT was the one left behind by the last planted
#      mutant. Nothing contradicted it, because the only thing that could have
#      was a rollup that predated the test's existence.
#
# So the scope of this gate is now the test suite's BOOKKEEPING, not just its
# membership: what is declared, what ran, and what each verdict artefact says
# must be three views of one state.
# ------------------------------------------------------------------

ROLLUP="results/tests/runall/Status.txt"
if [[ ! -f "$ROLLUP" ]]; then
  echo "TEST-MANIFEST: FAIL  the rollup $ROLLUP is missing"
  echo "  It is a TRACKED artefact; regenerate with: zsh tests/MUnit/run-tests.sh --all"
  STATUS=1
else
  rollup_line=$(head -1 "$ROLLUP")
  r_total=$(printf '%s\n' "$rollup_line" | sed -n 's/.*TOTAL=\([0-9]*\).*/\1/p')
  r_fail=$(printf '%s\n' "$rollup_line" | sed -n 's/.*FAIL=\([0-9]*\).*/\1/p')
  r_scope=$(printf '%s\n' "$rollup_line" | sed -n 's/.*SCOPE=\([A-Za-z0-9:_-]*\).*/\1/p')

  if [[ -z "$r_scope" ]]; then
    echo "TEST-MANIFEST: FAIL  the rollup carries no SCOPE= field: '$rollup_line'"
    echo "  It predates the scope fix, so it cannot be shown to be a FULL run."
    echo "  Regenerate with: zsh tests/MUnit/run-tests.sh --all"
    STATUS=1
  elif [[ "$r_scope" != "all" ]]; then
    echo "TEST-MANIFEST: FAIL  the rollup was written by a PARTIAL run (SCOPE=$r_scope)"
    echo "  Only a full run may stand as the whole-suite record."
    STATUS=1
  elif [[ -z "$r_total" ]]; then
    echo "TEST-MANIFEST: FAIL  the rollup has no TOTAL= field: '$rollup_line'"
    STATUS=1
  elif [[ "$r_total" -ne "$n_test" ]]; then
    echo "TEST-MANIFEST: FAIL  the runner scored ${r_total} tests, the manifest declares ${n_test}"
    echo "  A declared test that never ran is exactly the invisible class this manifest exists to end."
    echo "  Regenerate with: zsh tests/MUnit/run-tests.sh --all"
    STATUS=1
  else
    echo "TEST-MANIFEST: rollup agrees — ${r_total} scored / ${n_test} declared, SCOPE=${r_scope}"
  fi

  # Verdict artefacts must not contradict the rollup. Scanned over EVERY status
  # file under results/tests, so the denominator is printed and cannot be read
  # as zero.
  n_status=0
  orphan_fails=""
  while IFS= read -r sf; do
    [[ "$sf" == "$ROLLUP" ]] && continue
    n_status=$((n_status + 1))
    case "$(head -1 "$sf")" in
      FAIL*) orphan_fails="${orphan_fails}${sf}"$'\n' ;;
    esac
  done < <(find results/tests -type f -name 'Status*.txt' | sort)

  if [[ "$n_status" -eq 0 ]]; then
    echo "TEST-MANIFEST: REFUSED  found 0 status artefacts under results/tests."
    echo "  A scan over zero files is not a pass."
    exit 2
  fi

  if [[ -n "$orphan_fails" && "${r_fail:-0}" -eq 0 ]]; then
    echo "TEST-MANIFEST: FAIL  these artefacts read FAIL while the rollup reads FAIL=0:"
    printf '  %s\n' ${(f)orphan_fails}
    echo "  Either the rollup is stale, or a planted-mutant artefact was committed"
    echo "  in place of the restored run. Regenerate: zsh tests/MUnit/run-tests.sh --all"
    STATUS=1
  else
    echo "TEST-MANIFEST: verdict artefacts consistent — ${n_status} scanned, 0 contradict the rollup"
  fi
fi
[[ "$STATUS" -eq 0 ]] || echo "TEST-MANIFEST: the manifest does not account for the tree"
exit $STATUS
