"""
BioBridge.py
------------
Python-Mathematica Bridge for Causal Boolean Integration (Nature Protocol).

This module handles:
1.  Serialization of Biological Networks to JSON (for Mathematica consumption).
2.  Deserialization of Mathematica results (from JSON/CSV).
3.  Orchestration of the hybrid workflow.

Author: Alberto Hernández & Oxford Collaboration
Date: January 2026
"""

import json
import os
import subprocess
import numpy as np
from pathlib import Path
from typing import Dict, List, Any, Union

class BioBridge:
    def __init__(self, base_dir: str = None):
        if base_dir is None:
            # Default to project root assuming script is in src/integration
            self.base_dir = Path(__file__).resolve().parent.parent.parent
        else:
            self.base_dir = Path(base_dir)
            
        self.data_dir = self.base_dir / "data" / "bio"
        self.raw_dir = self.data_dir / "raw"
        self.processed_dir = self.data_dir / "processed"
        
        # Ensure directories exist
        self.raw_dir.mkdir(parents=True, exist_ok=True)
        self.processed_dir.mkdir(parents=True, exist_ok=True)

    def save_network_to_json(self, network_data: Dict[str, Any], filename: str) -> Path:
        """
        Save network data to JSON format compatible with Mathematica BioLink.
        
        Args:
            network_data: Dict containing 'nodes', 'edges', 'logic', 'cm' (optional)
            filename: Output filename (e.g., 'lambda_phage.json')
            
        Returns:
            Path to saved file
        """
        # Convert numpy arrays to lists for JSON serialization
        serializable_data = self._make_serializable(network_data)
        
        output_path = self.processed_dir / filename
        with open(output_path, 'w') as f:
            json.dump(serializable_data, f, indent=2)
            
        print(f"✓ [BioBridge] Network saved to {output_path}")
        return output_path

    def load_results_from_json(self, filename: str) -> Dict[str, Any]:
        """
        Load results generated by Mathematica.
        
        Args:
            filename: Input filename (e.g., 'lambda_phage_results.json')
            
        Returns:
            Dict containing results
        """
        input_path = self.processed_dir / filename
        if not input_path.exists():
            raise FileNotFoundError(f"Result file not found: {input_path}")
            
        with open(input_path, 'r') as f:
            data = json.load(f)
            
        print(f"✓ [BioBridge] Results loaded from {input_path}")
        return data

    def _make_serializable(self, obj: Any) -> Any:
        """Recursively convert numpy types to Python native types."""
        if isinstance(obj, dict):
            return {k: self._make_serializable(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._make_serializable(v) for v in obj]
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, (np.int64, np.int32)):
            return int(obj)
        elif isinstance(obj, (np.float64, np.float32)):
            return float(obj)
        else:
            return obj

    def check_mathematica_availability(self) -> bool:
        """Check if wolframscript is available in PATH."""
        try:
            subprocess.run(["wolframscript", "-code", "2+2"], 
                         capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

if __name__ == "__main__":
    # Self-test
    bridge = BioBridge()
    print(f"Bridge initialized at {bridge.base_dir}")
    print(f"Mathematica available: {bridge.check_mathematica_availability()}")
