#!/usr/bin/env python
"""Campaign status, derived from the ledgers (AUDIT01/T2.5).

Every campaign count quoted in README.md, FINDINGS.md and NEXT_PHASES.md must
come from THIS script's output — single source: `results/runs*.jsonl` plus the
committed mirror artifact `results/causalbool_mirror.json`. Before this script
existed the three documents disagreed with each other *and* with the ledgers
(README said 490 of 648 runs / 162 of 216 cases with several wrong per-model
gaps; FINDINGS and NEXT_PHASES said 607 runs / 202 of 216; the ledgers say
623 runs / 208 of 216 cells + 1 partial).

Design being measured (scripts/run_experiments.py): 3 models x 6 dataset
families x 2 modes x 6 noise levels x 3 replicates = 648 runs over 216 cells.
The size-bin study (`results/runs_sizebins.jsonl`, 24 replicates per cell) is a
separate ledger and is reported separately.

Run:
    .venv/bin/python scripts/campaign_status.py
"""

from __future__ import annotations

import collections
import datetime
import glob
import json
import os
import re
import subprocess
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(BASE, "results")

MAIN_LEDGERS = ["runs.jsonl", "runs_mixhop.jsonl", "runs_thop.jsonl"]
DATASETS = ["BACE", "BBBP", "ClinTox", "ESOL", "FreeSolv", "Lipophilicity"]
NOISES = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
MODES = [0, 1]
MODELS = ["t_hop", "mix_hop", "graphormer"]
REPS = 3


def collect_ledger():
    rows = []
    for name in MAIN_LEDGERS:
        path = os.path.join(RESULTS, name)
        for line in open(path):
            line = line.strip()
            if line:
                r = json.loads(line)
                r["_ledger"] = name
                rows.append(r)
    return rows


def main():
    rows = collect_ledger()
    cells = collections.defaultdict(list)
    for r in rows:
        cells[(r["model"], r["dataset"], r["use_path"], round(float(r["noise"]), 1))].append(r)

    total_cells = len(MODELS) * len(DATASETS) * len(MODES) * len(NOISES)
    total_runs = total_cells * REPS

    missing, partial, complete_cells = [], [], 0
    per_model_complete = {}
    for model in MODELS:
        ok = 0
        for ds in DATASETS:
            for mode in MODES:
                for noise in NOISES:
                    k = (model, ds, mode, noise)
                    n = len(cells.get(k, []))
                    if n == 0:
                        missing.append(k)
                    elif n < REPS:
                        partial.append((k, sorted(cells[k], key=lambda r: r["run"])))
                    else:
                        complete_cells += 1
                        ok += 1
        per_model_complete[model] = f"{ok}/{len(DATASETS) * len(MODES) * len(NOISES)}"

    sizebins_files = sorted(glob.glob(os.path.join(RESULTS, "runs_sizebins*.jsonl")))
    sizebins_runs = sum(sum(1 for line in open(f) if line.strip()) for f in sizebins_files)

    # mirror corpus (atom totals), from the committed artifact the mirror script wrote
    rec = json.load(open(os.path.join(RESULTS, "causalbool_mirror.json")))["recovery"]
    atoms = sum(v["atoms"] for v in rec.values())
    mols = sum(v["molecules"] for v in rec.values())
    exact = sum(v["exact"] for v in rec.values())
    capped = {k: v["molecules"] for k, v in rec.items() if v["molecules"] != 200}

    # pytest collection count
    n_tests = "?"
    try:
        out = subprocess.run([sys.executable, "-m", "pytest", "--collect-only"],
                             cwd=BASE, capture_output=True, text=True, timeout=300)
        m = re.search(r"(\d+) tests? collected", out.stdout + out.stderr)
        if m:
            n_tests = int(m.group(1))
    except Exception:
        pass

    L = []
    L.append("Campaign status (generated by scripts/campaign_status.py from "
             "results/runs*.jsonl and results/causalbool_mirror.json; "
             "single source: the ledgers — do not edit these lines by hand).")
    L.append(f"- runs: {len(rows)} of {total_runs}")
    L.append(f"- cells fully replicated ({REPS}/{REPS}): {complete_cells} of {total_cells}"
             f"; partial cells: {len(partial)}"
             + ("".join(f" [{m}/{ds} mode={mode} noise={noise}: {len(rs)}/{REPS}]"
                        for (m, ds, mode, noise), rs in partial) if partial else ""))
    if missing:
        by_model_mode = collections.defaultdict(list)
        for m, ds, mode, noise in missing:
            by_model_mode[(m, mode)].append((ds, noise))
        parts = []
        for (m, mode), items in sorted(by_model_mode.items()):
            dss = sorted({d for d, _ in items})
            parts.append(f"{m} mode={mode}: " + "; ".join(
                f"{d} noises {min(n for dd, n in items if dd == d):.1f}-{max(nn for dd, nn in items if dd == d):.1f}"
                if len([x for x in items if x[0] == d]) > 1 else
                f"{d} noise {items[[xx[0] for xx in items].index(d)][1]:.1f}" for d in dss))
        L.append(f"- missing cells ({len(missing)}): " + " | ".join(parts))
    else:
        L.append("- missing cells (0)")
    for model in MODELS:
        L.append(f"- per model {model}: {per_model_complete[model]} cells")
    L.append(f"- size-bin study (separate ledger results/runs_sizebins.jsonl): "
             f"{sizebins_runs} runs")
    L.append(f"- tests collected: {n_tests} (pytest --collect-only)")
    L.append(f"- mirror corpus: {atoms:,d} atoms over {mols:,d} molecules, exact "
             f"recovery {exact:,d}/{atoms:,d} = {100 * exact / atoms:.2f}% — corpus is "
             f"capped at the first 200 molecules per dataset"
             + (f" (smaller datasets: {', '.join(f'{k} {v}' for k, v in sorted(capped.items()))})"
                if capped else "") + "; cap location: scripts/causalbool_mirror.py graphs[:200]")

    block = "\n".join(L)
    print(block)
    with open(os.path.join(RESULTS, "campaign_status.txt"), "w") as fh:
        fh.write(block + "\n")
        fh.write(f"generated: {datetime.date.today().isoformat()}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
